### ISSUE TITLE
4.14 updates

### ISSUE THREAD

**Issue by borball** [borball/sno-agent-based-installer#10]
Check if all day1/day2 has any changes in 4.14.

**Comment by borball** [comment]
1. install-config: 
```
4.12: 

capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
    - marketplace

4.14:
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
    - marketplace
    - NodeTuning
```
2. PerformanceProfile
3.
