### ISSUE TITLE
network config refactoring

### ISSUE THREAD

**Issue by borball** [borball/sno-agent-based-installer#6]
old config:

```yaml 
ip: 192.168.58.48
dns: 192.168.58.15
gateway: 192.168.58.1
mac: b4:96:91:b4:9d:f0
prefix: 25
vlan:
  enabled: false
  name: ens1f0.58
  id: 58
```

new config:
```yaml
interface: ens1f0
mac: b4:96:91:b4:9d:f0
ipv4:
  enabled: true
  dhcp: false
  ip: 192.168.58.48
  dns: 192.168.58.15
  gateway: 192.168.58.1
  prefix: 25
  machine_network_cidr: 192.168.58.0/25
  #optional, default 10.128.0.0/14
  #cluster_network_cidr: 10.128.0.0/14
  #optional, default 23
  #cluster_network_host_prefix: 23
ipv6:
  enabled: false
  dhcp: false
  ip: 2600:52:7:58::48
  dns: 2600:52:7:58::15
  gateway: 2600:52:7:58::1
  prefix: 64
  machine_network_cidr: 2600:52:7:58::/64
  #optional, default fd01::/48
  #cluster_network_cidr: fd01::/48
  #optional, default 64
  #cluster_network_host_prefix: 64
vlan:
  enabled: false
  name: ens1f0.58
  id: 58
```
